config/routes.rb
Vitrine::Application.routes.draw do
  
  resources :devices

  resources :usuarios

  root :to => 'empresas#index'
  
  match 'empresas/conteudo/:identificador' => 'Empresas#get_conteudo_by_identificador'
  
  resources :empresas do
    resources :conteudos
  end
  
  get "empresas/index"

  resources :sessions
  
end

app/models/conteudo.rb
class Conteudo < ActiveRecord::Base
  
  
  belongs_to  :empresa, :foreign_key => "empresa_id", :class_name => "Empresa"
  belongs_to  :conteudo, :class_name => "Conteudo", :foreign_key => "parent_id"
  has_many    :counteudos, dependent: :destroy, :class_name => "Conteudo", :foreign_key => "parent_id"
  

  acts_as_tree :order => "id"
  
  #after_create :send_notification
  
  
  
  has_attached_file :imagem,
      :styles => {
      :thumb  => "100x100",
      :medium => "200x200",
      :large => "600x400",
      :icon => "42x42"
  },
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => ":attachment/:id/:style.:extension",
    :bucket => 'skynetimagens'

  has_attached_file :row_imagem,
      :styles => {
      :thumb  => "100x100",
      :medium => "200x200",
      :large => "600x400"
  },
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => ":attachment/:id/:style.:extension",
    :bucket => 'skynetimagens'
    
    
  def send_notification
    unless self.destaque == false || self.ativo == false
      #Apple notification
      unless self.empresa.token == nil
        APN.notify(self.empresa.token, :alert => self.titulo, :badge => 4, :sound => true, :other_information => self.subtitulo)
      end
       #Android c2dm
      unless self.empresa.c2dm_email == nil || self.empresa.c2dm_password == nil || self.empresa.c2dm_registration_id == nil
        SpeedyC2DM::API.set_account(self.empresa.c2dm_email, self.empresa.c2dm_password)
        options = {
          :registration_id => self.empresa.c2dm_registration_id,
          :message => self.titulo,
          :extra_data => self.id,
          :collapse_key => "some-collapse-key" #verificar o que é collapse-key
        }
        response = SpeedyC2DM::API.send_notification(options)
      end
    end
  end
  
  def as_json(options={})
     super(:methods => [:imagem_url, :imagem_thumb_url,:imagem_medium_url,:imagem_large_url,:imagem_icon_url,:row_imagem_url, :row_imagem_thumb_url,:row_imagem_medium_url,:row_imagem_large_url])
  end
    
    def imagem_url
        if imagem_updated_at != nil
          imagem.url
        end
    end

    def imagem_thumb_url
      if imagem_updated_at != nil
        imagem.url(:thumb)
      end
    end

    def imagem_medium_url
      if imagem_updated_at != nil
        imagem.url(:medium)
      end
    end

    def imagem_large_url
      if imagem_updated_at != nil
        imagem.url(:large)
      end
    end

    def imagem_icon_url
      if imagem_updated_at != nil
        imagem.url(:icon)
      end
    end

    def row_imagem_url
        if row_imagem_updated_at != nil
          row_imagem.url
        end
    end

    def row_imagem_thumb_url
      if row_imagem_updated_at != nil
        row_imagem.url(:thumb)
      end
    end

    def row_imagem_medium_url
      if row_imagem_updated_at != nil
        row_imagem.url(:medium)
      end
    end

    def row_imagem_large_url
      if row_imagem_updated_at != nil
        row_imagem.url(:large)
      end
    end 
end

app/controllers/conteudos_controller.rb
class ConteudosController < ApplicationController

  before_filter :get_empresa, :checar_permissoes_empresa_dependente

  require 'apn_on_rails'
  require 'configatron'
  
  def get_empresa
    @empresa = Empresa.find(params[:empresa_id])
  end
  
  # GET /conteudos
  # GET /conteudos.json
  def index
    @conteudos = @empresa.conteudos.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conteudos }
    end
  end

  # GET /conteudos/1
  # GET /conteudos/1.json
  def show
    @conteudo = @empresa.conteudos.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: [@empresa, @conteudo] }
    end
  end

  # GET /conteudos/new
  # GET /conteudos/new.json
  def new
    @conteudo = Conteudo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: [@empresa, @conteudo] }
    end
  end

  # GET /conteudos/1/edit
  def edit
    @conteudo = Conteudo.find(params[:id])
  end

  # POST /conteudos
  # POST /conteudos.json
  def create
    @conteudo = @empresa.conteudos.new(params[:conteudo])



    respond_to do |format|
      if @conteudo.save

        @devices = APN::Device.all
        @devices.each do |dev|
          app = APN::App.where(:id => dev.app_id)
          app.each do |ap|
            if (ap.apn_empresa_token == @empresa.token)
              configatron.apn.cert = File.join(RAILS_ROOT, 'config',  @empresa.token + "production.pem") #{}"/config/" + @empresa.token +  ".pem"
              notification = APN::Notification.new
              notification.device = dev
              notification.sound = true
              notification.alert = "Confira as novidades da Cholet!"
              notification.save
              APN::App.send_notifications
            end
          end

          format.html { redirect_to [@empresa, @conteudo], notice: 'Conteudo was successfully created.' }
          format.json { render json: [@empresa, @conteudo], status: :created, location: [@empresa, @conteudo] }

        end

      else
        format.html { render action: "new" }
        format.json { render json: @conteudo.errors, status: :unprocessable_entity }

        logger.info "Processing the request..."
      end
    end
  end

  # PUT /conteudos/1
  # PUT /conteudos/1.json
  def update
    @conteudo = @empresa.conteudos.find(params[:id])

    respond_to do |format|
      if @conteudo.update_attributes(params[:conteudo])
        format.html { redirect_to  [@empresa, @conteudo], notice: 'Conteudo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conteudo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conteudos/1
  # DELETE /conteudos/1.json
  def destroy
    @conteudo = Conteudo.find(params[:id])
    @conteudo.destroy

    respond_to do |format|
      format.html { redirect_to [@empresa, @conteudo] }
      format.json { head :no_content }
    end
  end
end

app/helpers/conteudos_helper.rb
module ConteudosHelper

	#concat('</br>'.html_safe)

	 def display_conteudos(conteudos)
       content_tag(:div, :class => 'container') do
       	conteudos.collect do |conteudo|
           	if conteudo.parent_id == nil
           		concat(
            		content_tag(:div, :class => 'conteudo', :id => 'accordion') do
            			 concat(
                        content_tag(:ul, :class => 'show') do link_to(image_tag("/assets/shared/show.png", :border=>0, :alt=> 'Mostrar Conteudo', :title => 'Mostrar Conteudo'), [@empresa,conteudo] ) end
                      )
                   concat(
                        content_tag(:ul, :class => 'editar') do link_to(image_tag("/assets/shared/editar.png", :border=>0, :alt=> 'Editar', :title => 'Editar'), edit_empresa_conteudo_path(@empresa,conteudo)) end
                      )
                  concat(
                        content_tag(:ul, :class => 'excluir') do link_to(image_tag("/assets/shared/remover.png", :border=>0, :alt=> 'Remover', :title => 'Remover'), [@empresa,conteudo], confirm: 'Tem certeza?', method: :delete) end
                      )
                  concact_conteudo(conteudo)
            			concat(find_all_subconteudos(conteudo))
                 
            		end
            	)
           	end
         	end
       end
    end
    
   def find_all_subconteudos(conteudo)
    if conteudo.children.size > 0
        content_tag(:div, :class => 'sub_conteudo') do
      	conteudo.children.collect do |subcat|
        	if subcat.children.size > 0
        		 
            concat(
          			content_tag(:div,:class => 'conteudo') do
                  concat(
                        content_tag(:ul, :class => 'show') do link_to(image_tag("/assets/shared/show.png", :border=>0, :alt=> 'Mostrar Conteudo', :title => 'Mostrar Conteudo'), [@empresa,subcat] ) end
                      )
          				concat(
                        content_tag(:ul, :class => 'editar') do link_to(image_tag("/assets/shared/editar.png", :border=>0, :alt=> 'Editar', :title => 'Editar'), edit_empresa_conteudo_path(@empresa,subcat)) end
                      )
                  concat(
                        content_tag(:ul, :class => 'excluir') do link_to(image_tag("/assets/shared/remover.png", :border=>0, :alt=> 'Remover', :title => 'Remover'), [@empresa,subcat], confirm: 'Tem certeza?', method: :delete) end
                      )
                  concact_conteudo(subcat)
          				concat(find_all_subconteudos(subcat))
          			end
          		)
        	else
        		concat(
          			content_tag(:div,:class => 'conteudo') do
                  concat(
                        content_tag(:ul, :class => 'show') do link_to(image_tag("/assets/shared/show.png", :border=>0, :alt=> 'Mostrar Conteudo', :title => 'Mostrar Conteudo'), [@empresa,subcat] ) end
                      )
          				concat(
                        content_tag(:ul, :class => 'editar') do link_to(image_tag("/assets/shared/editar.png", :border=>0, :alt=> 'Editar', :title => 'Editar'), edit_empresa_conteudo_path(@empresa,subcat)) end
                      )
                  concat(
                        content_tag(:ul, :class => 'excluir') do link_to(image_tag("/assets/shared/remover.png", :border=>0, :alt=> 'Remover', :title => 'Remover'), [@empresa,subcat], confirm: 'Tem certeza?', method: :delete) end
                      )
                  concact_conteudo(subcat)
          			end
          		)
        	end
        end
      end
    end
  end

  def concact_conteudo(conteudo)
  	concat(
      content_tag(:h3, conteudo.titulo, :class => 'label_header') do 

        concat(
          content_tag(:div) do

          concat(
            content_tag(:div) do image_tag(conteudo.imagem(:thumb), :class => 'image_conteudo_thumb') end
          )
          concat(
            content_tag(:div, conteudo.titulo, :class => 'label_titulo')
          )
          concat(
            content_tag(:div, conteudo.subtitulo, :class => 'label_subtitulo')
          )
          concat(
            content_tag(:div, conteudo.categoria, :class => 'label_categoria')
          )
          concat(
            content_tag(:div, conteudo.descricao.html_safe, :class => 'label_descricao')
          )
          
          
         end
         )
        
                
      end
      )
      
    content_tag(:div) do

          concat(
            content_tag(:li) do link_to('Editar', edit_empresa_conteudo_path(@empresa,conteudo)) end
          )

          concat(
            content_tag(:li) do link_to('Excluir', [@empresa,conteudo], confirm: 'Tem certeza?', method: :delete) end
          )
         
          concat(
            content_tag(:li) do image_tag(conteudo.imagem(:thumb), :class => 'image_conteudo_thumb') end
          )
        
          concat(
            content_tag(:li, conteudo.subtitulo, :class => 'label_subtitulo')
          )
         concat(
            content_tag(:li, conteudo.categoria, :class => 'label_categoria')
          )
         concat(
            content_tag(:li, conteudo.descricao, :class => 'label_descricao')
          )

         end
         
         
           
       
    
  end
  
end

app/views/conteudos/_form.html.erb
<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyAcEzpDs5fpjWQPAOSqaWsR2mhn6Svu_S0&sensor=true"></script> 
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "conteudos" %>
<%= stylesheet_link_tag 'widgEditor' %>
<%= javascript_include_tag "widgEditor" %>

<% unless @conteudo.ancestors.empty? %>
<p>
<% @conteudo.ancestors.reverse.each do |conteudo| %>
  <%= link_to conteudo.titulo, [@empresa,conteudo] %> &gt;
<% end %>
</p>
<% end %>

<div style="height: 30px;" >

<% unless @conteudo.children.empty? %>

<div style="float:left;">Conteudos</div>
<ul>
  <% @conteudo.children.reverse.each do |conteudo| %>
    <div style="float:left;margin-left:10px;"> >> <%= link_to conteudo.titulo, [@empresa,conteudo] %></div>
  <% end %>
</ul>
</div>
<% end %>


<%= form_for([@empresa, @conteudo], :html => { :multipart => true }) do |f| %>
  <% if @conteudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conteudo.errors.count, "error") %> Erro ao salvar:</h2>

      <ul>
      <% @conteudo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :parent_id %>
  <%= f.hidden_field :empresa_id %>
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>

<div style="padding-bottom:20px;width:200px;">

<%= link_to 'Ver', [@empresa,@conteudo] %> |
<%= link_to 'Voltar', empresa_conteudos_path(@empresa) %>
</div>


	<div class="caixaesquerda">
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
   <div class="field">
    <%= f.label :subtitulo %><br />
    <%= f.text_field :subtitulo %>
  </div>
  <div class="field">
    <%= f.label :ativo %><br />
    <%= f.check_box :ativo %>
  </div>
  <div class="field">
    <%= f.label :social %><br />
    <%= f.check_box :social %>
  </div>
  <div class="field">
    <%= f.label :destaque %><br />
    <%= f.check_box :destaque %>
  </div>
 
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br />
    <%= f.select :categoria, [['Galeria', 'galeria'], ['Imagem','imagem'], ['Menu','menu'], ['Lista', 'lista'], ['Localização', 'localzicacao'], ['Mapa', 'mapa'], ['Notícia', 'noticia'], ['Notícias', 'noticias'], ['Contato', 'contato'] , ['Videos', 'videos'], ['Web', 'web'], ['Social', 'social']] %>
  </div>
  </div>
  
  <div class="caixadireita">
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao, :cols => "50", :rows=>"3", :class=>"widgEditor" %>
  </div>
  
  <div class="field">
    <%= f.label :imagem %><br />
    <%= f.file_field :imagem %>
  </div>

  <div class="field">
    <%= f.label :row_imagem %><br />
    <%= f.file_field :row_imagem %>
  </div>

  <%if @empresa.conteudos %>
	<div class="field">
	   <%= f.label :parent_id %><br />
	   <%= f.select :parent_id, @empresa.conteudos.map{ |c| [c.titulo, c.id] },:include_blank => true %>
	</div>
	
  <% end %>
  <div class="field">
    <label for="locationTypeCheckbox">Local</label>
    <input id="locationTypeCheckbox" type="checkbox" value="false"/>
  </div>
	<div id="containerLocation">
		<div class="field">
		    <%= f.label :endereco %><br />
		    <%= f.text_field :endereco %>
		</div>
		<input type="button" id="geocodingButton" value="Geolocalizar">
		<div id="map"> 
		   <div id="map_canvas" style="width:100%; height:400px"></div>
		</div>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
   </div>
   
<% end %>

app/views/conteudos/edit.html.erb
<h1 style="margin-left:40%;margin-bottom:50px;">Editar conteudo</h1>



<div style="padding: 10px;
margin-left: 25%;

width: 800px;
margin-bottom: 30px;">
<%= render 'form' %>
</div>

app/views/conteudos/index.html.erb
<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyAcEzpDs5fpjWQPAOSqaWsR2mhn6Svu_S0&sensor=true"></script> 
<script src="http://code.jquery.com/jquery-1.8.2.js"></script>
    <script src="http://code.jquery.com/ui/1.9.1/jquery-ui.js"></script>
      <script>
     $(function() {
        $("#accordion").addClass("ui-accordion ui-widget ui-helper-reset ui-accordion-icons")
        .find("h3")
            .addClass("ui-accordion-header ui-helper-reset ui-state-default ui-corner-top ui-corner-bottom")
            .prepend('<span class="ui-icon ui-icon-triangle-1-e"/>')
            .click(function() {
                $(this).toggleClass("ui-accordion-header-active").toggleClass("ui-state-active")
                    .toggleClass("ui-state-default").toggleClass("ui-corner-bottom")
                .find("> .ui-icon").toggleClass("ui-icon-triangle-1-e").toggleClass("ui-icon-triangle-1-s")
                .end().next().toggleClass("ui-accordion-content-active").toggle();
                return false;
            })
            .next().addClass("ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom").hide();
    })
    </script>




	


<h1 style="margin-left:40%;margin-bottom:50px;">Lista de conteudos</h1>
<div  class="page-footer" style="padding:20px;margin-left:30px;">

<%= link_to 'Novo Conteúdo', new_empresa_conteudo_path(@empresa) %>




</div>

<div class="page-content">
<div class="page-table">
<table  id="content-table">
<%= display_conteudos(@conteudos) %>

</table>
</div>
</div>
<br />

app/views/conteudos/new.html.erb
<div style="padding:0px">

<h1 style="margin-left:40%;margin-bottom:50px;">Novo conteudo</h1>

<div style="padding: 10px;
margin-left: 25%;
width: 870px;
margin-bottom: 1400px;">
<%= render 'form' %>
</div>



</div>

app/views/conteudos/show.html.erb
<h1 style="margin-left:40%;margin-bottom:50px;">Novo conteudo</h1>

<div style="padding: 10px;
margin-left: 25%;
width: 800px;
margin-bottom: 30px;">


<p id="notice"><%= notice %></p>

<% unless @conteudo.ancestors.empty? %>
<p>
<% @conteudo.ancestors.reverse.each do |conteudo| %>
  <%= link_to conteudo.titulo, [@empresa,conteudo] %> &gt;
<% end %>
</p>
<% end %>

<% unless @conteudo.children.empty? %>

<div style="height: 30px;" >

<div style="float:left;">Conteúdos</div>
<ul>
  <% @conteudo.children.reverse.each do |conteudo| %>
    <div style="float:left;margin-left:10px;"> >> <%= link_to conteudo.titulo, [@empresa,conteudo] %></div>
  <% end %>
</ul>
</div>
<% end %>



<div style="padding-bottom:20px;">
<%= link_to 'Voltar', empresa_conteudos_path(@empresa) %> |
<%= link_to image_tag("/assets/shared/editar.png", :border=>0, :alt=> 'Editar', :title => 'Editar'), edit_empresa_conteudo_path(@empresa, @conteudo) %>
</div>


  <div class="caixaesquerda">
<p>
  <b>Titulo:</b>
  <%= @conteudo.titulo %>
</p>

<p>
  <b>Subtitulo:</b>
  <%= @conteudo.subtitulo %>
</p>

<p>
  <b>Categoria:</b>
  <%= @conteudo.categoria %>
</p>

<p>
  <b>Descricao:</b>
  <%= @conteudo.descricao.html_safe %>
</p>

<p>
  <b>Endereco:</b>
  <%= @conteudo.endereco %>
</p>
<p>
  <br/><br/>
   <h1>Imagens:</h1><br/>
  
  <b>Médio:</b><br/>
  <%= image_tag @conteudo.imagem.url(:medium) %><br/>
  <b>Thumb:</b><br/>
  <%= image_tag @conteudo.imagem(:thumb) %><br/>
  
  <b>Icone:</b><br/>
  <%= image_tag @conteudo.imagem(:icon) %><br/>
</p>



</div>
  <div class="caixadireita">
    <p>
  <b>Latitude:</b>
  <%= @conteudo.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @conteudo.longitude %>
</p>

<p>
  <b>Ativo:</b>
  <%= @conteudo.ativo %>
</p>

<p>
  <b>Destaque:</b>
  <%= @conteudo.destaque %>
</p>

<p>
  <b>Social:</b>
  <%= @conteudo.social %>
</p>

<p>
  <b>URL:</b>
  <%= @conteudo.url %>
</p>
<p>
  <br/>
  <h1>Celula imagens:</h1><br/>
  <b>Médio:</b><br/>
  <%= image_tag @conteudo.row_imagem.url(:medium) %><br/>
  <b>Thumb:</b><br/>
  <%= image_tag @conteudo.row_imagem(:thumb) %><br/>
</p>
</div>

</div>