config/routes.rb
Vitrine::Application.routes.draw do
  
  resources :devices

  resources :usuarios

  root :to => 'empresas#index'
  
  match 'empresas/conteudo/:identificador' => 'Empresas#get_conteudo_by_identificador'
  
  resources :empresas do
    resources :conteudos
  end
  
  get "empresas/index"

  resources :sessions
  
end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :deviceToken, :empresaToken

  validates :deviceToken, :presence => true, :uniqueness => {:scope => :empresaToken}

	validates_presence_of :deviceToken
	validates_presence_of :empresaToken
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json

  skip_before_filter :authorize
  require 'apn_on_rails'

  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    #@device = Device.new(params[:device])

    @empresa = Empresa.find(params[:device][:empresaToken])
    @device = Device.create(deviceToken: params[:device][:deviceToken], empresaToken: @empresa.token)


    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render json: @device, status: :created, location: @device }
        app = APN::App.where(:apn_empresa_token => @empresa.token).first
        APN::Device.create(:token => @device.deviceToken, :app_id => app.id)
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deviceToken %><br />
    <%= f.text_field :deviceToken %>
  </div>
  <div class="field">
    <%= f.label :empresaToken %><br />
    <%= f.text_field :empresaToken %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <tr>
    <th>Devicetoken</th>
    <th>Empresatoken</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @devices.each do |device| %>
  <tr>
    <td><%= device.deviceToken %></td>
    <td><%= device.empresaToken %></td>
    <td><%= link_to 'Show', device %></td>
    <td><%= link_to 'Edit', edit_device_path(device) %></td>
    <td><%= link_to 'Destroy', device, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Devicetoken:</b>
  <%= @device.deviceToken %>
</p>

<p>
  <b>Empresatoken:</b>
  <%= @device.empresaToken %>
</p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>