config/routes.rb
Vitrine::Application.routes.draw do
  
  resources :devices

  resources :usuarios

  root :to => 'empresas#index'
  
  match 'empresas/conteudo/:identificador' => 'Empresas#get_conteudo_by_identificador'
  
  resources :empresas do
    resources :conteudos
  end
  
  get "empresas/index"

  resources :sessions
  
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	belongs_to :empresa 
	validates_uniqueness_of :email
	validates_presence_of 	:email
	validates_uniqueness_of :cpf
	validates_presence_of 	:cpf

	def self.authenticate(email, senha)
    user = self.find_by_email(email)
    if user
      if user.senha != senha
        user = nil
      end
    end
    user
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_filter :get_empresas, :checar_permissoes_usuario
  
  def get_empresas
    @empresas = Empresa.all
  end

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="caixaesquerda">
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :rg %><br />
    <%= f.text_field :rg %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :senha %><br />
    <%= f.password_field :senha %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.telephone_field :telefone %>
  </div>
  </div>
  
  <div class="caixadireita">
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.select :tipo, [['Usuário', 'usuario'], ['Administrador','administrador'], ['Contratante','contratante']] %>
  </div>
  <%if @empresas %>
    <div class="field">
      <%= f.label :empresa_id %><br />
      <%= f.select :empresa_id, @empresas.map{ |c| [c.nome, c.id] },:include_blank => true %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1  style="margin-left:40%;margin-bottom:50px;">Editar usuario</h1>

<div style="margin-left:30%;">
<%= render 'form' %>
</div>

<div  class="page-footer" style="margin-left:30%;width:200px;">
<%= link_to 'Ver', @usuario %> |
<%= link_to 'Voltar', usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<div class="page-header">
  <h1 style="margin-left:40%;margin-bottom:50px;">Lista de usuários</h1>
  
</div>

<div class="page-content">
  <div class="page-table">
    <table id="content-table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th>Telefone</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @usuarios.each do |usuario| %>
            <tr>
                <td  style="width:30%;"><%= usuario.nome %></td>
                <td  style="width:30%;"><%= usuario.email %></td>
                <td><%= usuario.telefone %></td>
                <td><%= link_to image_tag("/assets/shared/show.png", :border=>0), usuario %></td>
                <td><%= link_to image_tag("/assets/shared/editar.png", :border=>0), edit_usuario_path(usuario) %></td>
                <td><%= link_to image_tag("/assets/shared/remover.png", :border=>0), usuario, confirm: 'Você tem certeza?', method: :delete %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
    <div class="page-footer">
        <%= link_to image_tag("/assets/shared/adicionar.png", :border=>0 , :alt => 'Adicionar nova empresa', :title => ''), new_usuario_path %>
    </div>
</div>

app/views/usuarios/new.html.erb
<h1 style="margin-left:40%;margin-bottom:50px;">Novo usuário</h1>

<div style="margin-left:25%;">
<%= render 'form' %>
</div>

<div  class="page-footer" style="margin-left:25%;width:200px;">
<%= link_to 'Voltar', usuarios_path %>
</div>

app/views/usuarios/show.html.erb
<div class="page-header">
  <h1 style="margin-left:40%;margin-bottom:50px;">Lista de usuários</h1>
</div>

<p id="notice"><%= notice %></p>
<div style="margin-left:30%;">
<p>
  <b>Nome:</b>
  <%= @usuario.nome %>
</p>

<p>
  <b>Cpf:</b>
  <%= @usuario.cpf %>
</p>

<p>
  <b>Rg:</b>
  <%= @usuario.rg %>
</p>

<p>
  <b>Email:</b>
  <%= @usuario.email %>
</p>

<p>
  <b>Senha:</b>
  <%= @usuario.senha %>
</p>

<p>
  <b>Telefone:</b>
  <%= @usuario.telefone %>
</p>

<div  class="page-footer" style="padding-top:10px;width:200px;">

<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Voltar', usuarios_path %>
</div>
</div>