config/routes.rb
Vitrine::Application.routes.draw do
  
  resources :devices

  resources :usuarios

  root :to => 'empresas#index'
  
  match 'empresas/conteudo/:identificador' => 'Empresas#get_conteudo_by_identificador'
  
  resources :empresas do
    resources :conteudos
  end
  
  get "empresas/index"

  resources :sessions
  
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  
  has_many    :conteudos, dependent: :destroy, :foreign_key => "empresa_id", :class_name => "Conteudo"
  has_many    :usuarios, dependent: :destroy, :foreign_key => "empresa_id", :class_name => "Usuario"
  validates_presence_of :identificador
  validates_uniqueness_of :identificador
  
  
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_filter :checar_permissoes_empresa, :except => :get_conteudo_by_identificador

  require 'apn_on_rails'

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @empresas }
    end
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @empresa }
    end
  end

  # GET /empresas/new
  # GET /empresas/new.json
  def new
    @empresa = Empresa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @empresa }
    end
  end

  # GET /empresas/1/edit
  def edit
    @empresa = Empresa.find(params[:id])
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(params[:empresa])

      if(!@empresa.token.empty?)
        if (!APN::App.where(:apn_empresa_token => @empresa.token).first)
          APN::App.create(:apn_empresa_token => @empresa.identificador, :apn_dev_cert =>  File.read('config/' + @empresa.token + "development.pem"), :apn_prod_cert => File.read('config/' + @empresa.token + "production.pem"))
        end
      end

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render json: @empresa, status: :created, location: @empresa }
      else
        format.html { render action: "new" }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /empresas/1
  # PUT /empresas/1.json
  def update
    @empresa = Empresa.find(params[:id])

    if(!@empresa.token.empty?)
      if (!APN::App.where(:apn_empresa_token => @empresa.token).first)
        APN::App.create(:apn_empresa_token => @empresa.identificador, :apn_dev_cert =>  File.read('config/' + @empresa.token + "development.pem"), :apn_prod_cert => File.read('config/' + @empresa.token + "production.pem"))
      end
    end

    respond_to do |format|
      if @empresa.update_attributes(params[:empresa])
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa = Empresa.find(params[:id])
    @empresa.destroy

    respond_to do |format|
      format.html { redirect_to empresas_url }
      format.json { head :no_content }
    end
  end
  
  def get_conteudo_by_identificador
    @empresa = Empresa.where("identificador = ?", params[:identificador])
    
    @conteudos = Conteudo.where("empresa_id = ?", @empresa)
    
    respond_to do |format|
      format.json { render :json => @conteudos }
    end
  end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<%= form_for(@empresa) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> Erro ao salvar:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="caixaesquerda">
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br />
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.telephone_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :identificador %><br />
    <%= f.text_field :identificador %>
  </div>
  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  </div>
  
  <div class="caixadireita">
   <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </div>
   <div class="field">
    <%= f.label :facebook %><br />
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :c2dm_email %><br />
    <%= f.text_field :c2dm_email %>
  </div>
  <div class="field">
    <%= f.label :c2dm_registration_id %><br />
    <%= f.text_field :c2dm_registration_id %>
  </div>
  <div class="field">
    <%= f.label :c2dm_password %><br />
    <%= f.password_field :c2dm_password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1 style="margin-left:40%;margin-bottom:50px;">Editar empresa</h1>

<div style="padding-bottom:10px;margin-left:30%;">
<%= render 'form' %>
</div>

<div  class="page-footer"  style="margin-left:30%;padding-top:10px;width:200px;">
<%= link_to 'Ver', @empresa %> |
<%= link_to 'Voltar', empresas_path %>
</div>

app/views/empresas/index.html.erb
<div class="page-header">
  <h1 style="margin-left:40%;margin-bottom:50px;">Lista de empresas</h1>
  
</div>

<div class="page-content">
  <div class="page-table">
    <table id="content-table">
      <thead>
        <tr>
          <th class="tl_nome" style="width:88%;">Nome</th>
          <th style="width:4%;"></th>
          <th style="width:4%;"></th>
          <th style="width:4%;"></th>
        </tr>
      </thead>
      <tbody>
        <% @empresas.each do |empresa| %>
          <tr>
            <td><%= empresa.nome %></td>
            <td><%= link_to image_tag("/assets/shared/show.png", :border=>0, :alt=> 'Mostrar', :title => 'Mostrar Conteudo'), empresa %></td>
            <td><%= link_to image_tag("/assets/shared/editar.png", :border=>0, :alt=> 'Editar', :title => 'Editar'), edit_empresa_path(empresa) %></td>
            <td><%= link_to image_tag("/assets/shared/remover.png", :border=>0 , :alt => 'Remover', :title => 'Remover'), empresa, confirm: 'Você tem certeza? ', method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="page-footer">
    <%= link_to image_tag("/assets/shared/adicionar.png", :border=>0 , :alt => 'Adicionar nova empresa', :title => 'Adicionar nova empresa'), new_empresa_path %>
  </div>
</div

app/views/empresas/new.html.erb
<div class="page-header">
	<h1 style="margin-left:40%;margin-bottom:50px;">Nova empresa</h1>
</div>



<div class="page-form" style="margin-left:30%;">
	<%= render 'form' %>

<div class="page-footer" style="margin-left:22%;float:left;">
<%= link_to 'Voltar', empresas_path %> 
</div>


</div>

app/views/empresas/show.html.erb
<div class="page-header">
	<h1 style="margin-left:40%;margin-bottom:50px;">Dados Cadastrais</h1>
</div>

<div style="margin-left:30%;width:500px;height:30px;">
<div  class="page-footer" style="padding-bottom:10px;float:left;">
<%= link_to 'Conteudos', empresa_conteudo_path(@empresa)[0..-2] %> 
</div>
<div style="float:left;padding-left:10px;display:block;">
</div>
<p id="notice"><%= notice %></p>
</div>
<div style="margin-left:30%;width:500px;border:1px solid #999;padding:10px;">
<p>
  <b>Nome:</b>
  <%= @empresa.nome %>
</p>

<p>
  <b>Cnpj:</b>
  <%= @empresa.cnpj %>
</p>

<p>
  <b>Telefone:</b>
  <%= @empresa.telefone %>
</p>

<p>
  <b>Email:</b>
  <%= @empresa.email %>
</p>

<p>
  <b>Identificador:</b>
  <%= @empresa.identificador %>
</p>

<p>
  <b>Apple token:</b>
  <%= @empresa.identificador %>
</p>
<p>
  <b>Twitter:</b>
  <%= @empresa.twitter %>
</p>
<p>
  <b>Facebook:</b>
  <%= @empresa.facebook %>
</p>
<p>
  <b>C2DM email:</b>
  <%= @empresa.c2dm_email %>
</p>

<p>
  <b>C2DM registration id:</b>
  <%= @empresa.c2dm_registration_id %>
</p>


</div>